mkv_video_formats_conversion = {
    "V_MS/VFW/FOURCC": "avi",
    "V_UNCOMPRESSED": "raw",
    "V_MPEG4/ISO/AVC": "h264",
    "V_MPEGH/ISO/HEVC": "hevc",
    "V_MPEG4/MS/V3": "mp4",
    "V_MPEG1": "mpg",
    "V_MPEG2": "mpg",
    "V_REAL/": "rm",
    "V_QUICKTIME": "mov",
    "V_THEORA": "ogv",
    "V_PRORES": "mov",
    "V_VP": "ivf",
    "V_DIRAC": "drc",
}
